adj_threshold: 0.0
aggregate_by: mean
batch_size: 32
d_emb: 0
d_ff: 32
d_hidden: 32
decoder_order: 1
epochs: 12
ff_dropout: 0.0
grad_clip_algorithm: norm
grad_clip_val: 5.0
in_sample: false
kernel_size: 2
l2_reg: 0.0
layer_norm: false
lr: 0.001
merge: mlp
model_name: grin
n_layers: 1
patience: 10
stride: 1
test_len: 0.2
val_len: 0.1
window: 48
